### ISSUE TITLE
Support SST ingestion in badger

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#107]
This feature is required for port Snapshot related code in TiKV

**Comment by coocood** [comment]
@bobotu

**Comment by bobotu** [comment]
Will complete this in three steps:
1. Add a RocksDB compatible `SST file writer/reader`.
1. Introduce a new meta field `FileGlobalTS` which represent the TS of keys in the ingested file.
   - Update SST file format.
   - Update `blockIterator` to use the global ts when reading a key from ingested files.
1. Add `IngestExternalFiles` function which converts files into badger's internal SST format and put them to the best level possible in the LSM-tree.

**Comment by coocood** [comment]
We need to add the license at the head of each file in this package.
