### ISSUE TITLE
`createWriteCmdOps` is not compatible with tikv

### ISSUE THREAD

**Issue by disksing** [ngaut/unistore#198]
It assumes that the raftcmd generated by the transaction write has a specific order, but when ran with tikv, the assumption is not true. For example, for prewrite, the write of lock cf may precede default cf. This causes unikv to fail to replicate data from tikv. In addition, this function is based on txnkv, which also makes it impossible to support rawkv.

https://github.com/ngaut/unistore/blob/7d1b4e2876fd5b35a53c713cbf26524507e5dfde/tikv/raftstore/fsm_apply.go#L960-L1052

**Comment by coocood** [comment]
It contradicts the code in tikv, can you take a deeper investigation?

**Comment by coocood** [comment]
RawKey is not supported for now.

**Comment by disksing** [comment]
After using the latest tikv, it seems all ok now.
