### ISSUE TITLE
support distributed deadlock detector

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#257]

**Comment by cfzjywxk** [comment]
the distributed deadlock detect mechanism implemented in `tikv` works as follows:

After the start of tikv-server, the deadlock detecting thread running with `Detector.run` method, this thread is responsible for handling `deadlock detection` tasks as well as `cleanup` tasks.
Initially, there will be one leader tikv electing using `pd-server`,  which will handle the tasks for the whole cluster. 

The processing  data stream:
1. `acquire_pessimistic_lock` ->  `Error::KeyIsLocked` 
2. The request is added to the `waiter_manager` as a lock waiter and the wait event is triggered. 
3. Then `on_wait_for_lock` handler will handle the wait event, in which the deadlock detection will be executed, this is executed in the `LockManager.wait_for`, the detection is only used for the non-first lock. 
4.  In `handle_detect`, the detection worker will decide to process locally or to send an RPC request to the detection leader.
5. The lock wait is described as an edge like  `txnTs`(node) -> `lockTs`(node), the deadlock detection is to check if there is another edge `lockTs` -> `txnTs`, which results in loop.
6. In `do_detect`, the util will use the `wait_for_ts` as the edge start, try to find one existing edge ending with the `txn_ts`, if found there will be deadlock and report deadlock error.
7. The `cleanup` will handle wakeup event if that the lock is already acquired, and the waiting edge has also an `ttl`.
