### ISSUE TITLE
assert failed in execCommit

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#277]
2019/11/19 12:30:18 Assert failed
github.com/coocood/badger/y.Assert
	/Users/zhou/gopath/pkg/mod/github.com/coocood/badger@v1.5.1-0.20191031155124-64a2ad772588/y/error.go:55
github.com/ngaut/unistore/tikv/raftstore.(*applier).execCommit
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/applier.go:1075
github.com/ngaut/unistore/tikv/raftstore.(*applier).execWriteCmd
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/applier.go:883
github.com/ngaut/unistore/tikv/raftstore.(*applier).execRaftCmd
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/applier.go:830
github.com/ngaut/unistore/tikv/raftstore.(*applier).applyRaftCmd
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/applier.go:758
github.com/ngaut/unistore/tikv/raftstore.(*applier).processRaftCmd
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/applier.go:729
github.com/ngaut/unistore/tikv/raftstore.(*applier).handleRaftEntryNormal
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/applier.go:647
github.com/ngaut/unistore/tikv/raftstore.(*applier).handleRaftCommittedEntries
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/applier.go:600
github.com/ngaut/unistore/tikv/raftstore.(*applier).handleApply
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/applier.go:1459
github.com/ngaut/unistore/tikv/raftstore.(*applier).handleTask
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/applier.go:1552
github.com/ngaut/unistore/tikv/raftstore.(*raftWorker).runApply
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/peer_state.go:263
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by cfzjywxk** [comment]
Reproducing this with https://github.com/pingcap/jepsen/tree/unistore @cfzjywxk

**Comment by cfzjywxk** [comment]
jepsen running one panic found at
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x101cbf1]

goroutine 148 [running]:
github.com/ngaut/unistore/tikv/raftstore.(*snapContext).applySnap(0xc0003778f0, 0x5, 0xc0000bebe8, 0xc0001b30e0, 0xc0001b3200, 0xc03cef0000, 0x0,  +++0x0, 0x0)
        /Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/worker.go:614 +0x5d1
github.com/ngaut/unistore/tikv/raftstore.(*snapContext).handleApply(0xc0003778f0, 0x5, 0xc0000bebe8, 0xc0001b30e0, 0xc0001b3200, 0x0,              +++0xc00a2f9040, 0x0, 0x0)
        /Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/worker.go:633 +0x82
github.com/ngaut/unistore/tikv/raftstore.(*regionRunner).handlePendingApplies(0xc00003a230)
        /Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/worker.go:840 +0x1f9
github.com/ngaut/unistore/tikv/raftstore.(*regionRunner).run(0xc00003a230, 0x192, 0x10d41c0, 0xc03d46aa50)
        /Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/worker.go:864 +0x10c
github.com/ngaut/unistore/tikv/raftstore.(*worker).start.func1(0xc0003775c0, 0x14e7400, 0xc00003a230)
        /Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/worker.go:208 +0xd3
created by github.com/ngaut/unistore/tikv/raftstore.(*worker).start
        /Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/worker.go:198 +0x6e

```

**Comment by cfzjywxk** [comment]
Another panic
peer.go:466: ^[[0;37m[info] [region 22] 23 destroy itself, takes 24.953063ms^[[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10060e2]

goroutine 125 [running]:
github.com/ngaut/unistore/tikv/raftstore.(*raftWorker).run(0xc0001391a0, 0xc0001d6a80, 0xc03c8f2100)
        /home/rwork/go/src/github.com/pingcap/unistore/tikv/raftstore/peer_state.go:152 +0x922
created by github.com/ngaut/unistore/tikv/raftstore.(*raftBatchSystem).startSystem
        /home/rwork/go/src/github.com/pingcap/unistore/tikv/raftstore/fsm_store.go:509 +0x160

**Comment by cfzjywxk** [comment]
Assertion fails will be triggered in all cases doing `kill-kv` operation
