### ISSUE TITLE
try separate old versions with new versions in badger SST.

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#383]
It may improve the performance of frequently updated entries.

**Comment by ngaut** [comment]
To introduce table properties should be a good idea. RocksDB has something like that.

**Comment by coocood** [comment]
@ngaut 
Yes, we can store table stats in the property, but I didn't get how table properties solve the old value problem?

**Comment by coocood** [comment]
Do you mean set old values into table property?
If there are many old values, the property would be too large.

**Comment by ngaut** [comment]
Could you store the old values into a separate SST file?

**Comment by coocood** [comment]
@ngaut 
Store in a separate SST file an option, but the number of old version entries may vary a lot.
If only a few old entries, store them in another file is not efficient.

We can also reserve some blocks for the old version, those blocks are usually never read.

**Comment by coocood** [comment]
The first step is done https://github.com/coocood/badger/pull/191

But it still iterates all versions.

Because we use `y.Iterator` interface to iterate values.

In order to skip old versions, all implementations of `y.Iterator` must support skip old versions.

So the next step is to change the SkipList to store old versions under the same key.
