### ISSUE TITLE
refine sst table format

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#473]
- Make block size fixed.
- Remove the index file.
- Add crc32 checksum.

**Comment by ngaut** [comment]
Why remove index file?

**Comment by coocood** [comment]
We separating index file and block file in the first place because we want to lazy load data block file from S3.

But S3's latency is too high to lazy load, we should fully load the file.

Then merge index file and block file into one can reduce the number of open files and number of requests.

**Comment by coocood** [comment]
Even after we merge index file and block file into one file, we can still partially load index data by specifying file range in S3 Get request.

**Comment by ngaut** [comment]
Index files can avoid load block data  from s3 when index showed the condition(such bloom filter) is not match.

**Comment by coocood** [comment]
> Index files can avoid load block data from s3 when index showed the condition(such bloom filter) is not match.

We can achieve the same goal with just one file.
