### ISSUE TITLE
Flush thread becomes bottle neck when use real S3.

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#609]
We only have one flush thread to flush mem-tables of all shards, so files are written to S3 sequentially.
Because writing a single file to S3 latency is high(about 300ms),  If the write workload is heavy, it becomes the bottleneck, then the flush channel will be full, blocks the apply thread.

To solve this problem, we should concurrently write files to S3 and sequentially produce the result.

**Comment by hslam** [comment]
Fixed by https://github.com/ngaut/unistore/pull/616
