### ISSUE TITLE
GetSplitSuggestion should consider mem-table and L0

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#626]
Currently, when the write workload is not perfectly sequential, we are not able to choose the bound key of MemTable as the split key. Then we only use the Ln tables boundary key as the split key.

If most of the data is in mem-table or L0, the split key may not be able to effectively split the shard, cause the shard keeps growing.

**Comment by coocood** [comment]
One algorithm I came up with would look like this:

When the Ln table's total size is not larger than a certain ratio, like 70%, we use the middle key of the latest L0 table's write CF as the split key.

**Comment by hslam** [comment]
Fixed by https://github.com/ngaut/unistore/pull/627
