### ISSUE TITLE
Still have incorrect skip flush change set because of commitTS inconsistency.

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#630]
[ERROR] [meta.go:276] ["223:33 skip duplicated flush commitTS:763501, meta commitTS:763502"]

**Comment by coocood** [comment]
CommitTS is used as the version of Lock CF and also used to order the L0 files.

In order to complete solve the inconsistency problem, we should remove the commitTS and use the raft log index instead.

**Comment by coocood** [comment]
The newly split region's initial raft log index should inherent the parent region's raft log index, so the old L0 table's sequence will always be smaller than new L0 table's sequence.

**Comment by hslam** [comment]
Changing the initial index of a raft group may cause some potential problems. In kv engine, adding parent index to shard may be a better choice. Using the new split region's index plus parent index as the commit timestamp. The commit timestamp will keep increments sequentially from the old region to the new region.

**Comment by hslam** [comment]
Fixed by https://github.com/ngaut/unistore/pull/632
